<a href="https://colab.research.google.com/github/namnitha/CE888-Data-Science/blob/master/Lab1/Lab1_Task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Lab1 Task

1. Create a (4 x 2) integer array and print it's attributes


In [7]:
import numpy as np
a=np.array([[1,2],[5,6],[9,10],[13,14]])
print(a)
print(a.shape)

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]]
(4, 2)


####2.Create an array of dimension (1,10) and sort it in ascending and descending order

In [14]:
b=np.array([5,3,7,2,3,8,1,7,0,4])
Asc= np.sort(b)
print(Asc)
Des= Asc[::-1]
print(Des)

[0 1 2 3 3 4 5 7 7 8]
[8 7 7 5 4 3 3 2 1 0]


####3.Convert an 1D array [1 2 3 4 5 6 7 8 9] to 2D array [[1 2 3], [4 5 6], [7 8 9]]

In [27]:
c=np.array([1,2,3,4,5,6,7,8,9])
# def to_matrix(l, n):return [l[i:i+n] for i in xrange(0, len(l), n)]
# to_matrix(c,2)
c = c.reshape((3,3))
print(c)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


4.Stack two arrays of any size horizontally and vertically

In [31]:
c=np.array([1,2,3,4])
b=np.array([5,3,7,2])
np.hstack((c,b))
np.vstack((c,b))

array([[1, 2, 3, 4],
       [5, 3, 7, 2]])

####5.create two array of same size and find commom elements

In [32]:
print(np.intersect1d(b, c))

[2 3]


####6.Create a 2D array of 5 by 5 and find the min and max values from each row and each column

In [64]:
d=np.array([[1,2,3,4,5],[5,6,7,8,9],[9,10,1,2,3],[13,14,4,5,6]])
#maxValue = np.amax(d)
#minValue = np.amin(d)
#print(maxValue)
#print(minValue)
for i in d:
  print(np.amax(i))
  print(np.amin(i))

for i in d.T:
   print(np.amax(i))
   print(np.amin(i)) 

5
1
9
5
10
1
14
4
13
1
14
2
7
1
8
2
9
3


####7.Create an array of size 100 and compute the mean, median, standard deviation.



In [51]:
a= np.random.rand(100)
b=np.mean(a)
print(b)
c=np.median(a)
print(c)
d=np.std(a)
print(d)

0.4964570415944525
0.5009541922324412
0.29575352920923736


####8.Normalize a 5x5 random matrix

In [54]:
a= np.random.rand(5,5)
print(a)
amax,amin= a.max(), a.min()
a=(a-amin)/(amax-amin)
print("normalized array")
print(a)

[[0.07889372 0.99205202 0.12613909 0.23823705 0.37040226]
 [0.67636726 0.22847926 0.64233292 0.5851668  0.82905863]
 [0.2551326  0.11676689 0.31585307 0.48210537 0.45372063]
 [0.23281283 0.46374361 0.59587725 0.28595353 0.20120794]
 [0.38230471 0.19211752 0.61458584 0.63295137 0.49637723]]
normalized array
[[0.         1.         0.05173843 0.17449694 0.31923112]
 [0.6542935  0.16381118 0.61702248 0.55441985 0.82150587]
 [0.19299927 0.04147493 0.25949428 0.44155723 0.4104731 ]
 [0.16855688 0.42144926 0.56614886 0.22675128 0.13394636]
 [0.33226549 0.12399143 0.58663664 0.60674874 0.45718635]]


####9.Consider an array of dimension (4,4,3), how to mulitply it by an array with dimensions (4,4)?

In [62]:
a= np.random.rand(4,4,3)
print(a)
a=a.reshape(12,4)
print(a)
b= np.random.rand(4,4)
print(b)
print(np.dot(a,b))

[[[0.43511356 0.2629572  0.33396888]
  [0.71995741 0.2968472  0.47166398]
  [0.69510435 0.44286075 0.01405876]
  [0.5745169  0.17034457 0.19874036]]

 [[0.79730375 0.64278855 0.31337605]
  [0.61724522 0.70410359 0.34417847]
  [0.99748515 0.41670013 0.17300782]
  [0.18247433 0.38259757 0.58886403]]

 [[0.88311672 0.48230135 0.46483326]
  [0.31543069 0.50250502 0.01903488]
  [0.31275302 0.2217541  0.14272693]
  [0.54210323 0.21558228 0.51110312]]

 [[0.98574157 0.14958065 0.11354298]
  [0.12713505 0.7669728  0.46546746]
  [0.93080565 0.73174446 0.40461837]
  [0.37123951 0.56433738 0.45794296]]]
[[0.43511356 0.2629572  0.33396888 0.71995741]
 [0.2968472  0.47166398 0.69510435 0.44286075]
 [0.01405876 0.5745169  0.17034457 0.19874036]
 [0.79730375 0.64278855 0.31337605 0.61724522]
 [0.70410359 0.34417847 0.99748515 0.41670013]
 [0.17300782 0.18247433 0.38259757 0.58886403]
 [0.88311672 0.48230135 0.46483326 0.31543069]
 [0.50250502 0.01903488 0.31275302 0.2217541 ]
 [0.14272693 0.54210323 